# Generated by Django 6.0 on 2025-12-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('se_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaturas',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
